config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#top'
  resources :users, only: [:index,:show, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, length: { minimum: 2, maximum:20}
  validates :name, presence: true
  validates :introduction, length: { maximum:50}


  # has_many :post_images, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  def email_required?
   false
 end
 def email_changed?
   false
 end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!
 before_action :correct_user, only: [:edit, :update]
  def index
    @users = User.all
    @user = current_user
    @book = Book.all
    @book = Book.new
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @books = @user.books.all
    @book = Book.new
  end

  def new
    @user = User.new
  end

  def create

  end

  def edit
    @user = User.find(params[:id])
  end

  def user_params
  params.require(:user).permit(:profile_image, :introduction)
  end

  def update
    @user = User.find(params[:id])
    puts @user
    if @user.update(user_params)
    flash[:notice] = "Book was successfully"
    redirect_to user_path(@user.id)
  else
    @users = User.all
    render :edit
  end
end

private 
def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
end

def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="body">
  <div class="container">
    <p id="notice"></p>
    <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>2 errors prohibited this book from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
    <h2>User info</h2>
    <%= form_for(@user) do |f| %>
    <div class="field">
      <label for="user name">Name</label>
        <%= f.text_field :name, id:"user_name", placeholder:"名前"%>
    </div>
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>

    <div class="field">
    <label for="user_image">Image</label>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
    </div>
    <div class="field">
    <label>Introduction</label>
    <%= f.text_area :introduction, class: 'form-control' %>
    </div>
    <div class="actions">
    <%= f.submit "Update user", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
  </div>
<% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
<p id="notice"></p>
<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
    <table class="table">
<tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= @user.name %></th>
    </tr>
    <tr>
      <th>Introduction</th>
      <th><%= @user.introduction %></th>
    </tr>
</tbody>
</table>
<div class="row">
　　 <% if @user.id == current_user.id %>
        <%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    <% end %>
</div>

<h2>New book</h2>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2>2 errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for(@book) do |f| %>
  <div class="field row">
  <label for="book_title">title</label>
  <%= f.text_field :title, class:"col-xs-12 book_title" %>
  </div>
  <div class="field row">
  <label for="book_opinion">Opinion</label>
  <%= f.text_area :body, class:"col-xs-12 book_title" %>
  </div>
  <div class="actions row">
  <%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
  <% end %>
</div>
</div>

<div class="col-xs-9">
<h2>Users</h2>
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
    </thead>
<tbody>
<% @users.each do |user| %>
<tr>
	<td>
    <%= attachment_image_tag user,:profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg"%><be />
    </td>
    <td>
    <%=user.name %><be />
    </td>
    <td>
    <%= link_to "Show", user_path(user) %>
    </td>
<% end %>
</tr>
</tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
    <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
      <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
      <th><%= @user.introduction %></th>
      </tr>
    </tbody>
    </table>
    <div class="row">
        <%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    </div>

<h2>New book</h2>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2>2 errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@book) do |f| %>
  <div class="field row">
  <label for="book_title">title</label>
  <%= f.text_field :title, class:"col-xs-12 book_title" %>
  </div>
  <div class="field row">
  <label for="book_opinion">Opinion</label>
  <%= f.text_area :body, class:"col-xs-12 book_title" %>
  </div>
  <div class="actions row">
  <%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
<% end %>
</div>
</div>

<div class="col-xs-9">
<h2>Books</h2>
<table class="table table-hover table-inverse">
<thead>
  <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
  </tr>
</thead>
<tbody>
<% @books.each do |book| %>
       <tr>
       <td>
        <%= link_to user_path do %>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
        <% end %>
       </td>
       <td>
        <%= link_to book_path(book) do %>
        <%= book.title %>
        <% end %>
       </td>
       <td>
        <%= book.body %>
       </td>
      </tr>
    <% end %>
  </table>
</div>
</div>
</tbody>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>