config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#top'
  resources :users, only: [:index,:show, :edit, :update]
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	# attachment :image
	# has_many :post_image, dependent: :destroy
validates :title, presence: true
validates :body, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :authenticate_user!
 before_action :correct_user, only: [:edit, :update]
  def index
    @users = User.all
  	@books = Book.all
  	@book = Book.new
    @user_profile = current_user
  end

  def show
    @books = Book.all
    @book_new = Book.new
  	@book = Book.find(params[:id])
    @user = @book.user
    @user_profile = current_user
  end

  def destroy
  	book = Book.find(params[:id])
    book.destroy
  	flash[:notice] = "Book was successfully destroyed."
  	redirect_to books_path
  end

  def new
  	@books = Book.new
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
  	if @book.save
  	flash[:notice] = "Book was successfully created."
  	redirect_to book_path(@book.id)
  	else
  		@books = Book.all
      @user = current_user
  		render :index
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @user_profile = current_user
  end

  def update
  	@book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book.id)
    else
  		@books = Book.all
  		render :edit
    end
  end


  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end

  def correct_user
    book = Book.find(params[:id])
    if book.user_id != current_user.id
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <nav class="nav navbar-nav navbar-left">
    <span>Bookers</span>
  </nav>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li>
       <a class="glyphicon glyphicon-home home" href="/user/id"> Home</a>
      </li>
      <li>
        <a class="glyphicon glyphicon-user users" href="/users">
        Users</a>
      </li>
      <li>
        <a class="glyphicon glyphicon-book books" href="/books">Books</a>
      </li>
      <li>
        <a class="glyphicon glyphicon-log-out logout" rel="nofollow" data-method="delete" href="/users/sign out">logout</a>
      </li>
    </ul>
  </nav>
</div>
</header>

app/views/books/edit.html.erb
<div class="body">
  <div class="container">
    <div class="row">
    <div class="col-md-6 col-md-ofset-3">
    <h1>Editing Book</h1>
	<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2>2 errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
    <%= form_for(@book) do |f| %>
    <div class="field row">
    <label for="book_title">Title</label>
    <%= f.text_field :title %>
    </div>

    <div class="field row">
    <label for="book_body">Opinion
    </label>
    <%= f.text_field :body %>
    </div>
    <div class="actions">
    <%= f.submit 'Update book', class:"btn btn-primary" %>
    </div>
    <% end %>
    <td>
     <%= link_to "Show", book_path(@book) %>
    </td>
	|
	<%= link_to "Back", books_path %>
  <div class="col-md-3">
  </div>
</div>
</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container">
    <p id="notice"></p>
    <div class="row">
      <div class="col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
    <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= current_user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th></th>
      <%= current_user.introduction %>
      </tr>
  </tbody>
  </table>
  <div class="row">
    <%= link_to "", edit_user_path(current_user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
  </div>

 <h2>New book</h2>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2>2 errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for(@book) do |f| %>
  <div class="field row">
  <label for="book_title">title</label>
  <%= f.text_field :title, class:"col-xs-12 book_title" %>
  </div>
  <div class="field row">
  <label for="book_opinion">Opinion</label>
  <%= f.text_area :body, class:"col-xs-12 book_body" %>
 </div>
  <div class="actions row">
  <%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
 <% end %>
</div>
</div>

    <div class="col-xs-9">
    <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
       <tr>
         <th>Title</th>
         <th>Opinion</th>
         <th colspan="3"></th>
       </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
       <tr>
       <td>
        <%= link_to user_path(book.user) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>

       </td>
       <td>
        <%= link_to book_path(book) do %>
        <%= book.title %>
        <% end %>
       </td>
       <td>
        <%= book.body %>
       </td>
      </tr>
    <% end %>
    <% end %>
 </tbody>
</table>
</div>
</div>
</div>

app/views/books/new.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <nav class="nav navbar-nav navbar-left">
    <span>Bookers</span>
  </nav>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li>
       <%=link_to "Home", user_path(@user), class:"glyphicon glyphicon-home home" %>
     </li>
      <li>
        <a class="glyphicon glyphicon-user users" href="/users">
        Users</a>
      </li>
      <li>
        <a class="glyphicon glyphicon-book books" href="/books">Books</a>
      </li>
      <li>
        <a class="glyphicon glyphicon-log-out logout" rel="nofollow" data-method="delete" href="/users/sign_out">logout</a>
      </li>
    </ul>
  </nav>
</div>
</header>

<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
    <table class="table">
    <tbody>
      <p>name</p>
      <p><span><%= @user.name %></span>
      </p>
      <p>Introduction</p>
      <p><%= @user.introduction %></p>
        <p><%= link_to "", edit_user_path(@user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
</div>

<div class="body">
  <div class="container">
    <p id="notice"></p>
    <div class="row">
      <div class="col-xs-3">


        <h2>New book</h2>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2>2 errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for(@book) do |f| %>

  <h4>title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>

<% end %>

  <p id="notice"></p>
    <div class="col-xs-9">
    <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <p id="notice"></p>
  <h1>Books</h1>
  <table>
    <thead>
       <tr>
         <th>Title</th>
         <th>Opinion</th>
         <th colspan="3"></th>
       </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
       <tr>
       <td>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
       </td>
       <td>
        <a href ="/book/#{book.id}(@books)">
        <%= book.title %>
      </a>
       </td>
       <td>
        <%= book.body %>
       </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  </div>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
<% if flash[:notice] %>
	  <p id="notice"><%= flash[:notice] %></p>
	<% end %>

  <div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
    <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th> <%= @user.name %></th>
      </tr>
      <tr>
        <th>Introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
    </table>
    <div class="row">
      <% if current_user.id == @user.id%>
        <%= link_to "", edit_user_path(@user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
      <% end %>
    </div>

<h2>New book</h2>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2>2 errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@book_new) do |f| %>
  <div class="field row">
    <label for="book_title">title</label>
    <%= f.text_field :title, class:"col-xs-12 book_title"%>
  </div>
  <div class="field row">
  <label for="book_opinion">Opinion</label>
  <%= f.text_area :body , class:"col-xs-12 book_title" %>
  </div>
  <div class="actions row">
  <%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
  <% end %>
  </div>
</div>

  <div class="col-xs-9">
  <h2>Book detail</h2>
  <table class="table">
	  <tbody>
      <tr>
        <td>
          <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
          <%= link_to user_path(@user) do %></br>
          <%= @user.name %>
          <% end %>
        </td>
        <td>
	        <strong>Title:</strong>
	        <%= @book.title %>
	      </td>
	      <td>
	        <strong>Opinion:</strong>
	        <%= @book.body %>
	      </td>
        <td>
        <% if current_user.id == @user.id%>
      <%= link_to "Edit", edit_book_path(@book), class:"btn-sm btn-success"%>
      <%= link_to "Destroy", book_path(@book),class:"btn-sm btn-danger", method: :delete, "data-confirm" => "Are you sure?" %>
      <% end %>
      </td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>